language: cpp
matrix:
  include:
    - os: osx
      osx_image: xcode10
      env:
        - MATRIX_EVAL="brew install qt5"

before_install:
  - eval "${MATRIX_EVAL}"
script:
 - /usr/local/opt/qt/bin/qmake
 - make

